[tool.basedpyright]
reportMissingTypeStubs = false
reportUnusedCallResult = false
reportUnknownMemberType = false
reportUnknownVariableType = false
reportUnknownArgumentType = false
reportAny = false
pythonVersion = "3.12"